#!/bin/bash

set -e

#Cloning repo
git clone git@github.com:rafaelcamargo/ng-rise.git;

#Acessing project
echo 'Opening project...';
cd ng-rise;

#Removing installing script
rm -rf install;

#Installing dev dependencies
echo 'Installing dependencies...';
npm install;

#Installing app dependencies
echo 'Building dependencies...';
grunt build;

# getting current open browser command
case $( uname -s ) in
Darwin)  open=open;;
MINGW*)  open=start;;
CYGWIN*) open=cygstart;;
*)       open=xdg-open;;
esac

#Opening app
echo 'Opening browser...';
$open http://localhost:9000/;

#Starting dev mode
echo 'ng-rise started!';
grunt start;
